v1 = input('Digite algo: ')
print('Qual o tipo primitivo? ', type(v1))
print('Só tem espaços? ', v1.isspace())
print('É um número: ', v1.isalnum())
print('É alfabético? ', v1.isalpha())
print('É alfanumérico? ',v1.isalnum())
print('Está em maisculas? ', v1.isupper())
print('Está capitalizada? ', v1.istitle())
